### ISSUE TITLE
Todo : Windows : envoi des données par la lumière

### ISSUE THREAD

**Issue by balllou** [balllou/STEG_rubber_ducky#2]
L'idée est de parser le fichier CSV pour en faire une chaine binaire qu'on pourra ensuite envoyer via notre canal caché : l'écran

- [x] script qui parse un csv en chaîne binaire
- [x] faire varier la luminosité de l'écran en fonction de cette chaîne

**Comment by balllou** [comment]
pas de solution rapide pour afficher le binaire du fichier texte -> affichage de l'hexa et passage par une table de conversion hex/bin

**Comment by balllou** [comment]
Policy par défaut pour powershell -> ne pas exécuter de scripts custom
voir pour faire un .exe

**Comment by balllou** [comment]
string parse powershell : 
https://www.sqlshack.com/powershell-split-a-string-into-an-array/

**Comment by Nidavelis** [comment]
Faire varier la luminosité de l'écran 👍 
powercfg -SetDcValueIndex 381b4222-f694-41f0-9685-ff5bb260df2e 7516b95f-f776-4464-8c53-06167f40cc99 aded5e82-b909-4619-9949-f5d71dac0bcb 100

powercfg -S 381b4222-f694-41f0-9685-ff5bb260df2e

**Comment by balllou** [comment]
code uploadé et fonctionnel sur branche windows -> fermeture de l'issue
